version: '3.8'

services:
  pgdatabase:
    image: postgres:14
    container_name: pg_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ingest:
    build: .
    container_name: ingest_container
    depends_on:
      - pgdatabase
    volumes:
      - .:/app
    command: >
      sh -c "
      python upload_zones.py &&
      python ingest.py
      "

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase

volumes:
  pgdata:
